version: "3"
services:
  cmd:
    container_name: arbitrage-htc
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    env_file: .env
    volumes:
      - .config.json:/.config.json
      - ./logs:/logs
      - ./imgs:/imgs
