version: "3"
services:
  cmd:
    container_name: arbitrage-htc
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    volumes:
      - ./config.yaml:/config.yaml
      - ./logs:/logs
